apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeapi-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pokeapi-ui
  template:
    metadata:
      labels:
        app: pokeapi-ui
    spec:
      containers:
      - image: docker.io/library/pokeapi:0.1
        name: pokeapi
        ports:
        - containerPort: 3000
        env:
          - name: POKEDEX_NAME
            valueFrom:
              configMapKeyRef:
                name: pokeapi-cm
                key: POKEDEX_NAME
          - name: POKEDEX_START_NUMBER
            valueFrom:
              configMapKeyRef:
                name: pokeapi-cm
                key: POKEDEX_START_NUMBER
          - name: POKEDEX_END_NUMBER
            valueFrom:
              configMapKeyRef:
                name: pokeapi-cm
                key: POKEDEX_END_NUMBER
